---
- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - audacious
      - calibre
      - curl
      - evince
      - filezilla
      - firefox
      - gimp
      - git
      - gitk
      - gnome-disk-utility
      - gnome-system-monitor
      - gparted
      - gthumb
      - ibus
      - inkscape
      - libreoffice
      - meld
      - mplayer
      - nemo
      - network-manager-openvpn
      - openjdk-17-jdk
      - poedit
      - pulseaudio
      - pulseaudio-module-bluetooth
      - pv
      - rar
      - snap
      - terminator
      - thunderbird
      - ttf-mscorefonts-installer
      - ubuntu-restricted-extras
      - vim
      - vlc
      - whois
  become: true

- name: Remove unwanted packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - abiword
      - apport
      - apport-gtk
      - catfish
      - gigolo
      - gnome-mines
      - gnome-sudoku
      - gnumeric
      - leafpad
      - lxterminal
      - midori
      - mousepad
      - nano
      - parole
      - ristretto
      - sylpheed
      - thunar
      - transmission
      - transmission-gtk
      - transmission-common
      - wine
      - xfburn
      - xfce4-notes
      - xfce4-notes-plugin
      - xpad
  become: true