---
- name: Install tlp
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - tlp
      - tlp-rdw
  become: true

- name: Enable tlp with systemctl
  shell: /usr/bin/systemctl enable tlp
  become: true